//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluguels
    {
        public int Id { get; set; }
        public System.DateTime DataHoraRetirada { get; set; }
        public System.DateTime DataHoraDevolucao { get; set; }
        public int CarroId { get; set; }
        public int ClienteId { get; set; }
        public int ProtecaoId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Carroes Carroes { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Protecaos Protecaos { get; set; }
        public virtual Status Status { get; set; }
    }
}
