//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carroes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carroes()
        {
            this.Aluguels = new HashSet<Aluguels>();
        }
    
        public int Id { get; set; }
        public string Placa { get; set; }
        public string Descricao { get; set; }
        public double PrecoDia { get; set; }
        public int ModeloId { get; set; }
        public string Imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aluguels> Aluguels { get; set; }
        public virtual Modeloes Modeloes { get; set; }
        public virtual Modeloes Modeloes1 { get; set; }
    }
}
