//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leis()
        {
            this.Votocandidatolei = new HashSet<Votocandidatolei>();
        }
        
        public int Id { get; set; }
        [Display(Name = "Número")]
        [Required]
        public string Numero { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 10)]        
        public string Nome { get; set; }
        [Required]
        [MaxLength(215)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Votocandidatolei> Votocandidatolei { get; set; }
    }
}
