//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGRADOUROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGRADOUROS()
        {
            this.PESSOAS = new HashSet<PESSOAS>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Pais_Id { get; set; }
        public int Estado_Id { get; set; }
        public int Municipio_Id { get; set; }
        public int Bairro_Id { get; set; }
        public string Cep { get; set; }
    
        public virtual BAIRROS BAIRROS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual MUNICIPIOS MUNICIPIOS { get; set; }
        public virtual PAISES PAISES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESSOAS> PESSOAS { get; set; }
    }
}
