//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Logradouros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Logradouros()
        {
            this.Pessoas = new HashSet<Pessoas>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public int Bairro { get; set; }
        [Required]
        public Nullable<int> Cidade { get; set; }
        [Required]
        public Nullable<int> Estado { get; set; }
        [Required]
        [Display(Name = "País")]
        public Nullable<int> Pais { get; set; }
    
        public virtual Bairros Bairros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoas> Pessoas { get; set; }
        public virtual Cidades Cidades { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
