//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocadoraCarrosDBEntities : DbContext
    {
        public LocadoraCarrosDBEntities()
            : base("name=LocadoraCarrosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Aluguels> Aluguels { get; set; }
        public virtual DbSet<Carroes> Carroes { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Funcaos> Funcaos { get; set; }
        public virtual DbSet<Funcionarios> Funcionarios { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Modeloes> Modeloes { get; set; }
        public virtual DbSet<Protecaos> Protecaos { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
