//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PESSOAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESSOAS()
        {
            this.CANDIDATOCARGO = new HashSet<CANDIDATOCARGO>();
            this.FAVORIOS = new HashSet<FAVORIOS>();
            this.FAVORIOS1 = new HashSet<FAVORIOS>();
            this.PRESIDENTES = new HashSet<PRESIDENTES>();
            this.PRESIDENTES1 = new HashSet<PRESIDENTES>();
            this.VOTOCANDIDATOLEI = new HashSet<VOTOCANDIDATOLEI>();
            this.VOTOS = new HashSet<VOTOS>();
            this.VOTOS1 = new HashSet<VOTOS>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Cpf { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> Ativo { get; set; }
        public string Email { get; set; }
        public string TelefoneFixo { get; set; }
        public string TelefoneMovel { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> Pais_Id { get; set; }
        public Nullable<int> Estado_Id { get; set; }
        public Nullable<int> Municipio_Id { get; set; }
        public Nullable<int> Bairro_Id { get; set; }
        public Nullable<int> Logradouro_Id { get; set; }
        public string Cep { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }

        public enum EnTipo { Candidato = 1, Funcionario = 2, Usuario = 3 };
        public int Tipo { get; set; }        

        public virtual BAIRROS BAIRROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATOCARGO> CANDIDATOCARGO { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORIOS> FAVORIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORIOS> FAVORIOS1 { get; set; }
        public virtual LOGRADOUROS LOGRADOUROS { get; set; }
        public virtual MUNICIPIOS MUNICIPIOS { get; set; }
        public virtual PAISES PAISES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESIDENTES> PRESIDENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESIDENTES> PRESIDENTES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTOCANDIDATOLEI> VOTOCANDIDATOLEI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTOS> VOTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTOS> VOTOS1 { get; set; }
    }
}
