//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTOCANDIDATOLEI
    {
        public int Id { get; set; }
        public int Candidato_Id { get; set; }
        public int Lei_Id { get; set; }
        public int Votou { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual LEIS LEIS { get; set; }
        public virtual PESSOAS PESSOAS { get; set; }
    }
}
